resources:
  - release/kubernetes-manifests.yaml
  - httproute.yaml
images:
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/frontend
    newName: host.docker.internal:5000/microservices-demo/frontend
    newTag: 3ac8c79
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/paymentservice
    newName: host.docker.internal:5443/microservices-demo/paymentservice
    digest: sha256:a19addfd853eeaa7b5d721a659595e4e47ebf8ff7286697a387386567f4c0ea7
patches:
  - path: delete-frontend-external.yaml
